### ISSUE TITLE
Cannot import stylesheet using esbuild

### ISSUE THREAD

**Issue by greeeg** [Wondermarin/react-color-palette#53]
### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| Node.JS version             | v18.9.1   |
| react-color-palette version | v7.0.0   |

Heyy 👋 
I'm having trouble importing `react-color-palette/css` as it does not directly point to a css file using `esbuild` & `esbuild-sass-plugin`. I noticed that the `exports` change was made in `v7`. Could it be possible to expose the real file & its real path in `exports`?

Many thanks!

```
Error: Build failed with 1 error:
#10 97.69 ssr/server_rendering.ts:4:7: ERROR: [plugin: sass-plugin] Can't find stylesheet to import.
#10 97.69    ╷
#10 97.69 10 │ @import 'react-color-palette/css';
#10 97.69    │         ^^^^^^^^^^^^^^^^^^^^^^^^^
#10 97.69    ╵
#10 97.69   - 10:9  root stylesheet
#10 97.69     at failureErrorWithLog (/xxx/node_modules/esbuild/lib/main.js:1649:15)
#10 97.69     at /xxx/node_modules/esbuild/lib/main.js:1058:25
#10 97.69     at /xxx/node_modules/esbuild/lib/main.js:1525:9
#10 97.69     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
#10 97.69   errors: [
#10 97.69     {
#10 97.69       detail: undefined,
#10 97.69       id: '',
#10 97.69       location: [Object],
#10 97.69       notes: [],
#10 97.69       pluginName: 'sass-plugin',
#10 97.69       text: "Can't find stylesheet to import.\n" +
#10 97.69         '   ╷\n' +
#10 97.69         "10 │ @import 'react-color-palette/css';\n" +
#10 97.69         '   │         ^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
#10 97.69         '   ╵\n' +
#10 97.69         '  - 10:9  root stylesheet'
#10 97.69     }
#10 97.69   ],
#10 97.69   warnings: []
#10 97.69 }
```

**Comment by Wondermarin** [comment]
@greeeg, should be fixed in v7.0.1

**Comment by greeeg** [comment]
@Wondermarin You're the best, thanks & have a great weekend!

**Comment by PadowYT2** [comment]
Having this issues with webpack on v7.1.0:
```
ERROR in ./resources/scripts/components/admin/pages/Colors.tsx
Module not found: Error: Can't resolve 'react-color-palette/css' in '/var/www/test/resources/scripts/components/admin/pages'
 @ ./resources/scripts/components/admin/pages/Colors.tsx 15:0-33
 @ ./resources/scripts/components/admin/pages/index.tsx
 @ ./resources/scripts/components/admin/Sidebar.tsx
 @ ./resources/scripts/components/admin/Layout.tsx
 @ ./resources/scripts/components/App.tsx
 @ ./resources/scripts/index.tsx
 @ multi react-hot-loader/patch ./resources/scripts/index.tsx
```

`import 'react-color-palette/dist/css/rcp.css';` works fine
